# Generated by Django 6.0.6 on 2026-07-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Human-readable study title, e.g. 'Flanker task'.", max_length=200)),
                ('slug', models.SlugField(help_text='Short URL-safe identifier; appears in the study URL, e.g. /study/flanker/.', unique=True)),
                ('code', models.TextField(help_text="The researcher's jsPsych timeline code (JavaScript).")),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'studies',
                'ordering': ['-created'],
            },
        ),
    ]
