# Generated by Django 6.0.6 on 2026-07-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_participant_session_trial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='study',
            name='researchers',
            field=models.ManyToManyField(blank=True, help_text='The researcher(s) who own this study.', related_name='studies', to='study.researcher'),
        ),
    ]
