# Generated by Django 6.0.6 on 2026-07-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_researcher_study_researchers'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='completion_url',
            field=models.URLField(blank=True, default='', help_text='Where participants go when they finish, e.g. your Prolific completion URL. Leave blank to just show a thank-you.'),
        ),
    ]
