# Generated by Django 6.0.6 on 2026-07-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0005_study_completion_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='accepting_responses',
            field=models.BooleanField(default=True, help_text='Untick to close the study: it stops accepting submissions and stops serving to participants (you can still preview it).'),
        ),
    ]
