# Generated by Django 6.0.6 on 2026-07-13 19:32

from django.db import migrations, models


def list_existing_studies(apps, schema_editor):
    # New studies are unlisted by default, but the studies that already exist when this
    # runs (the seeded Flanker/Stroop demos) should stay visible on the index.
    Study = apps.get_model("study", "Study")
    Study.objects.update(is_listed=True)


def unlist_all(apps, schema_editor):
    Study = apps.get_model("study", "Study")
    Study.objects.update(is_listed=False)


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0006_study_accepting_responses'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='is_listed',
            field=models.BooleanField(default=False, help_text="Show this study on the public index page. New studies are unlisted by default; tick this once it's ready for the public. An unlisted study is still reachable by its direct link, it just isn't advertised on the index."),
        ),
        migrations.RunPython(list_existing_studies, unlist_all),
    ]
