# Generated by Django 6.0.6 on 2026-07-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0007_study_is_listed'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='require_participant_id',
            field=models.BooleanField(default=False, help_text="Refuse runs that arrive without a participant_id in the URL. Tick this for recruitment-platform studies (e.g. Prolific), where a response you can't match to a submission is useless."),
        ),
    ]
