# Generated by Django 6.0.6 on 2026-07-17 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0008_study_require_participant_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trial',
            name='session',
        ),
        migrations.CreateModel(
            name='StudyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(blank=True, max_length=100)),
                ('data', models.JSONField(help_text='The whole jsPsych run: a list of trial objects.')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datasets', to='study.participant')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='study.study')),
            ],
            options={
                'verbose_name_plural': 'study data',
                'ordering': ['-created'],
            },
        ),
        migrations.DeleteModel(
            name='Session',
        ),
        migrations.DeleteModel(
            name='Trial',
        ),
    ]
