# Generated by Django 6.0.6 on 2026-07-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0009_studydata'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='plugins',
            field=models.JSONField(blank=True, default=list, help_text="The jsPsych plugins this study's timeline uses. Choose none to load them all, which is handy while you're drafting but slower for participants."),
        ),
    ]
