# Generated by Django 6.0.6 on 2026-07-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0011_seed_plugins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='external_id',
            field=models.CharField(blank=True, help_text="The participant_id passed in the study URL, e.g. ?participant_id=p01. Clear it to cut the link to the recruitment platform while keeping this person's runs grouped together.", max_length=200, null=True, unique=True),
        ),
    ]
