# Generated by Django 6.0.6 on 2026-08-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0012_alter_participant_external_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='accepting_responses',
        ),
        migrations.RemoveField(
            model_name='study',
            name='is_listed',
        ),
        migrations.RemoveField(
            model_name='study',
            name='plugins',
        ),
        migrations.RemoveField(
            model_name='study',
            name='require_participant_id',
        ),
        migrations.AlterField(
            model_name='participant',
            name='external_id',
            field=models.CharField(blank=True, help_text='The participant_id passed in the study URL', max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='study',
            name='completion_url',
            field=models.URLField(blank=True, default='', help_text='Where participants go when they finish, e.g. your Prolific completion URL. Leave blank to just show a thank-you message.'),
        ),
    ]
