# Generated by Django 6.1.1 on 2026-09-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0013_remove_study_accepting_responses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='code',
            field=models.TextField(blank=True, default='', help_text="The researcher's jsPsych timeline code (JavaScript)."),
        ),
    ]
